accounts/urls.py
from django.urls import path
from .views import (
    UserListView,
    UserCreateView,
    UserUpdateView,
    UserDeleteView,
    UserDetailView,
    ProfileUpdateView,
    OrganizationListView,
    OrganizationCreateView,
    OrganizationUpdateView,
    OrganizationDeleteView,
    OrganizationDetailView,
)

app_name = "accounts"

urlpatterns = [
    path("", UserListView.as_view(), name="users"),
    path("create/", UserCreateView.as_view(), name="create"),
    path("<str:slug>/update/", UserUpdateView.as_view(), name="user-update"),
    path("<str:slug>/delete/", UserDeleteView.as_view(), name="user-delete"),
    path("<str:slug>/", UserDetailView.as_view(), name="user-detail"),
    path(
        "profile/<int:pk>/update/", ProfileUpdateView.as_view(), name="profile-update"
    ),
    path("organizations/", OrganizationListView.as_view(), name="organization-list"),
    path(
        "organizations/create/",
        OrganizationCreateView.as_view(),
        name="organization-create",
    ),
    path(
        "organizations/<int:pk>/update/",
        OrganizationUpdateView.as_view(),
        name="organization-update",
    ),
    path(
        "organizations/<int:pk>/delete/",
        OrganizationDeleteView.as_view(),
        name="organization-delete",
    ),
    path(
        "organizations/<int:pk>/",
        OrganizationDetailView.as_view(),
        name="organization-detail",
    ),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("dashboard.urls")),
    path("users/", include("accounts.urls")),
    path("contacts/", include("contacts.urls")),
    path("cases/", include("cases.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0]
    )

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_countries.fields import CountryField

from utils.enum import UserType
from utils.mixins import AddressAndPhoneNumberMixin, SlugMixin, TimestampMixin


class User(AbstractUser,  SlugMixin,TimestampMixin):
    email = models.EmailField(unique=True)
    organization = models.ForeignKey(
        "accounts.Organization", on_delete=models.CASCADE, null=True, blank=True
    )
    is_superadmin = models.BooleanField(default=False)
    user_type = models.CharField(
        max_length=20, choices=UserType.choices, default=UserType.NORMAL
    )
    country = CountryField(default=None, null=True)
    hourly_rate = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    phone_number = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=50, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "first_name", "last_name"]


class Profile(AddressAndPhoneNumberMixin, SlugMixin, TimestampMixin, models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.get_full_name()


class Organization(AddressAndPhoneNumberMixin, SlugMixin, TimestampMixin, models.Model):
    name = models.CharField(max_length=100)
    superadmin = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="superadmin_of"
    )
    country = CountryField(default=None, null=True)
    created_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        null=True,
        related_name="org_created",
    )

    def __str__(self):
        return self.name


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    client_organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="client_organization"
    )

    def __str__(self):
        return self.user.get_full_name() or self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User, Profile, Organization

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Field, Submit, Button
from django.urls import reverse_lazy
from django import forms
from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "email",
            "username",
            "first_name",
            "last_name",
            "user_type",
            "country",
            "hourly_rate",
            "phone_number",
            "address",
            "password1",  # Add password1 field
            "password2",  # Add password2 field
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.form_class = "form-horizontal"
        # self.helper.label_class = "col-md-4 col-form-label"
        self.helper.field_class = "col-md-8"
        self.helper.field_class = "form-control"

        self.helper.layout = Layout(
            Row(
                Column("first_name", css_class="col-md-6"),
                Column("last_name", css_class="col-md-6"),
            ),
            Row(
                Column("email", css_class="col-md-6"),
                Column("username", css_class="col-md-6"),
            ),
            Row(
                Column("user_type", css_class="col-md-6"),
                Column("country", css_class="col-md-6"),
            ),
            Row(
                Column("hourly_rate", css_class="col-md-4"),
                Column("phone_number", css_class="col-md-4"),
                Column("address", css_class="col-md-4"),
            ),
            Row(
                Column("password1", css_class="col-md-6"),
                Column("password2", css_class="col-md-6"),
            ),
            Row(
                Column(
                    Submit("submit", "Save", css_class="btn btn-success mx-2"),
                    Button(
                        "cancel",
                        "Cancel",
                        css_class="btn btn-secondary mx-2",
                        onclick="window.location.href='{}'".format(
                            reverse_lazy("accounts:users")
                        ),
                    ),
                    css_class="d-flex justify-content-center mt-3",
                ),
            ),
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "email",
            "username",
            "first_name",
            "last_name",
            "user_type",
            "country",
            "hourly_rate",
            "phone_number",
            "address",
            "password",  # Add password field
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.layout = Layout(
            Row(
                Column("first_name", css_class="col-md-6"),
                Column("last_name", css_class="col-md-6"),
            ),
            Row(
                Column("email", css_class="col-md-6"),
                Column("username", css_class="col-md-6"),
            ),
            Row(
                Column("user_type", css_class="col-md-6"),
                Column("country", css_class="col-md-6"),
            ),
            Row(
                Column("hourly_rate", css_class="col-md-4"),
                Column("phone_number", css_class="col-md-4"),
                Column("address", css_class="col-md-4"),
            ),
            Row(
                Column("password", css_class="col-md-6"),  # Add password field
            ),
            Row(
                Column(
                    Submit("submit", "Save", css_class="btn btn-success mx-2"),
                    Button(
                        "cancel",
                        "Cancel",
                        css_class="btn btn-secondary mx-2",
                        onclick="window.location.href='{}'".format(
                            reverse_lazy("accounts:users")
                        ),
                    ),
                    css_class="d-flex justify-content-center mt-3",
                ),
            ),
        )


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"


class OrganizationForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = "__all__"

accounts/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
)
from .models import Client, User, Profile, Organization
from .forms import (
    CustomUserCreationForm,
    CustomUserChangeForm,
    ProfileForm,
    OrganizationForm,
)


class UserListView(ListView):
    model = User
    template_name = "accounts/user_list.html"
    context_object_name = "users"


class UserCreateView(CreateView):
    model = User
    form_class = CustomUserCreationForm
    template_name = "accounts/user_form.html"
    success_url = reverse_lazy("accounts:users")

    def form_valid(self, form):
        user = form.save()
        messages.success(self.request, f"{user.username} successfully added.")
        return super().form_valid(form)


class UserUpdateView(UpdateView):
    model = User
    form_class = CustomUserChangeForm
    template_name = "accounts/user_form.html"
    success_url = reverse_lazy("accounts:users")

    def form_valid(self, form):
        user = form.save()
        messages.success(self.request, f"{user.username.title()} successfully updated.")
        return super().form_valid(form)


class UserDeleteView(DeleteView):
    model = User
    template_name = "accounts/user_confirm_delete.html"
    success_url = reverse_lazy("accounts:users")

    def form_valid(self, form):
        messages.success(self.request, f"Successfully deleted.")
        return super().form_valid(form)


class UserDetailView(DetailView):
    model = User
    template_name = "accounts/user_detail.html"


class ProfileUpdateView(UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = "accounts/profile_form.html"
    success_url = reverse_lazy("accounts:users")


class OrganizationListView(ListView):
    model = Organization
    template_name = "accounts/organization_list.html"
    context_object_name = "organizations"


class OrganizationCreateView(CreateView):
    model = Organization
    form_class = OrganizationForm
    template_name = "accounts/organization_form.html"
    success_url = reverse_lazy("organization-list")


class OrganizationUpdateView(UpdateView):
    model = Organization
    form_class = OrganizationForm
    template_name = "accounts/organization_form.html"
    success_url = reverse_lazy("organization-list")


class OrganizationDeleteView(DeleteView):
    model = Organization
    template_name = "accounts/organization_confirm_delete.html"
    success_url = reverse_lazy("organization-list")


class OrganizationDetailView(DetailView):
    model = Organization
    template_name = "accounts/organization_detail.html"


class ClientCreateView(CreateView):
    model = Client
    fields = ["user", "organization"]
    template_name = "users/client_form.html"
    success_url = "/clients/"


# class ClientListView(LoginRequiredMixin, ListView):
class ClientListView(ListView):

    model = Client
    template_name = "users/client_list.html"
    context_object_name = "clients"

templates/accounts/user_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">Delete User</h1>
      </div>
    </div>
  </div>
</div>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <form method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Delete</button>
              <a href="{% url 'accounts:users' %}" class="btn btn-secondary"
                >Cancel</a
              >
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/user_detail.html
{% extends 'base.html' %} {% block content %}
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">User Detail</h1>
      </div>
    </div>
  </div>
</div>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <p><strong>Username:</strong> {{ object.username }}</p>
            <p><strong>Email:</strong> {{ object.email }}</p>
            <p><strong>First Name:</strong> {{ object.first_name }}</p>
            <p><strong>Last Name:</strong> {{ object.last_name }}</p>
            <p><strong>User Type:</strong> {{ object.user_type }}</p>
            <p><strong>Country:</strong> {{ object.country }}</p>
            <a href="{% url 'accounts:user-update' object.slug %}" class="btn btn-warning"
              >Edit</a
            >
            <a href="{% url 'accounts:users' %}" class="btn btn-secondary"
              >Back</a
            >
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/user_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="app-content-header">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6"><h3 class="mb-0">Dashboard</h3></div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-end">
          <li class="breadcrumb-item"><a href="{% url "accounts:users" %}">All Users</a></li>
          <li class="breadcrumb-item active" aria-current="page">Manage Users</li>
        </ol>
      </div>
    </div>
  </div>
</div>
<div class="app-content">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-header border-0">
            <div class="d-flex justify-content-center">
              <h3 class="card-title"><h2>{% if form.instance.pk %}Edit {{form.instance.first_name|title}}'s details {% else %}Create User{% endif %}</h3>
            </div>
          </div>
          <div class="card-body">
            <div class="d-flex">
              <form method="post">
                {% csrf_token %}
                {% crispy form %}
              </form>
            </div>
          </div>
        </div>        
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/user_list.html
{% extends 'base.html' %}
{% block content %}
<div class="app-content-header">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6"><h3 class="mb-0">All Users</h3></div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-end">
          <a href="{% url "accounts:create" %}"><li class="breadcrumb-item btn btn-success text-white fw-bold">Add User</li></a>
        </ol>
      </div>
    </div>
  </div>
</div>
<div class="app-content">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-lg-12">
        <div class="card mb-4">
          <div class="card-body">
              <table id="tbl-user-list" class="table table-bordered table-striped dataTable dtr-inline w-100" aria-describedby="example1_info">
                <thead>
                    <tr>
                        <th class="sorting sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Username: activate to sort column descending">
                            Username
                        </th>
                        <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="First name: activate to sort column ascending">First name</th>
                        <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Last name: activate to sort column ascending">Last name</th>
                        <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="email: activate to sort column ascending">Email Address</th>
                        <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Action: activate to sort column ascending">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr class="{% cycle 'odd' 'even' %}">
                        <td class="dtr-control sorting_1" tabindex="0">{{ user.username|title }}</td>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.last_name }}</td>
                        <td>{{ user.email }}</td>
                        <td>
                            <a href="{% url 'accounts:user-update' user.slug %}" class="btn btn-sm btn-warning">Edit</a>
                            <a href="{% url 'accounts:user-delete' user.slug %}" class="btn btn-sm btn-danger">Delete</a>
                            <a href="{% url 'accounts:user-detail' user.slug %}" class="btn btn-sm btn-info">View</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <th rowspan="1" colspan="1">Username</th>
                        <th rowspan="1" colspan="1">First name</th>
                        <th rowspan="1" colspan="1">Last name</th>
                        <th rowspan="1" colspan="1">Email Address</th>
                        <th rowspan="1" colspan="1">Action</th>
                    </tr>
                </tfoot>
              </table>
          </div>
        </div>        
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}
<script>
  $(document).ready( function () {
    $('#tbl-user-list').DataTable();
  });
</script>
{% endblock extra_js %}